/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labo;

import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import static java.time.temporal.TemporalQueries.localDate;
import java.util.ArrayList;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author pc
 */
public class ETAT_BIOCHIMIE extends javax.swing.JFrame {

   
     

   

    
 
    /**
     * Creates new form ETAT_BIOCHIMIE
     */
    public ETAT_BIOCHIMIE() {
        initComponents();
       
        txt_date.requestFocus();
         
     DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate localDate = LocalDate.now();
        txt_date.setText(localDate.toString());
      
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_prenom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        BIOCHIMIE = new javax.swing.JPanel();
        txt_uree = new javax.swing.JTextField();
        uree = new javax.swing.JLabel();
        creatine = new javax.swing.JLabel();
        txt_creatine = new javax.swing.JTextField();
        glicimee = new javax.swing.JLabel();
        txt_glycemie = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txt_calcymie = new javax.swing.JTextField();
        lipide = new javax.swing.JLabel();
        txt_lipide = new javax.swing.JTextField();
        txt_cholesterol = new javax.swing.JTextField();
        cholesterol = new javax.swing.JLabel();
        triglicide = new javax.swing.JLabel();
        txt_triglyceride = new javax.swing.JTextField();
        txt_protine = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        acide = new javax.swing.JLabel();
        txt_acide = new javax.swing.JTextField();
        txt_amylase = new javax.swing.JTextField();
        amylase = new javax.swing.JLabel();
        txt_sgot = new javax.swing.JTextField();
        sgot = new javax.swing.JLabel();
        sgpt = new javax.swing.JLabel();
        txt_sgpt = new javax.swing.JTextField();
        directe = new javax.swing.JLabel();
        txt_directe = new javax.swing.JTextField();
        txt_libre = new javax.swing.JTextField();
        inderecte = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        txt_totale = new javax.swing.JTextField();
        txt_phosph = new javax.swing.JTextField();
        phosphat = new javax.swing.JLabel();
        phosphore = new javax.swing.JLabel();
        txt_phosphor = new javax.swing.JTextField();
        soduim = new javax.swing.JLabel();
        txt_sodium = new javax.swing.JTextField();
        potasuim = new javax.swing.JLabel();
        txt_potasium = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTXT_DESCRIPTION = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        txt_date = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("CABINET MEDICAL * عيــــــــادة طبيــــــــة ");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الدكتور كيشو تاج الدين");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("طب عام");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("MEDECINE   GENERALE-ECHOGRAPHIE-EXPLORATION");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dr.KICHOU TADJEDDINE");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("NOM ET PRENOM:");

        txt_prenom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_prenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_prenom.setBorder(null);
        txt_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_prenomActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("AGE:");

        txt_age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_age.setBorder(null);
        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });
        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ageKeyPressed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("CITE AL MOSTAKBAL N°214       BENI  ABBES BECHAR");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("TEL/FAX: 049-28-61-61               MOBILE:   06-68-15-04-14/ 06-60-01-51-48");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        txt_nom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nom.setBorder(null);
        txt_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nomKeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("BIOCHIMIE");

        BIOCHIMIE.setBackground(new java.awt.Color(255, 255, 255));

        txt_uree.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_uree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_uree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ureeActionPerformed(evt);
            }
        });
        txt_uree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_ureeKeyPressed(evt);
            }
        });

        uree.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        uree.setText("Urée (0,20-0,40 g/l)");
        uree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        creatine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        creatine.setText("Créatinine (8-12mg/l)");
        creatine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_creatine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_creatine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_creatine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_creatineActionPerformed(evt);
            }
        });
        txt_creatine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_creatineKeyPressed(evt);
            }
        });

        glicimee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        glicimee.setText("Glycémie (0,65-0,90g/l)");
        glicimee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_glycemie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_glycemie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_glycemie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_glycemieActionPerformed(evt);
            }
        });
        txt_glycemie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_glycemieKeyPressed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Calcémie (90-110mg/l)");
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_calcymie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_calcymie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_calcymie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_calcymieActionPerformed(evt);
            }
        });
        txt_calcymie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_calcymieKeyPressed(evt);
            }
        });

        lipide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lipide.setText("Lipides totaux (5,5-7,5 g/l)");
        lipide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_lipide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_lipide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_lipide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lipideActionPerformed(evt);
            }
        });
        txt_lipide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_lipideKeyPressed(evt);
            }
        });

        txt_cholesterol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_cholesterol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cholesterol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cholesterolActionPerformed(evt);
            }
        });
        txt_cholesterol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cholesterolKeyPressed(evt);
            }
        });

        cholesterol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cholesterol.setText("Cholestérol (1,4-2,7 g/l)");
        cholesterol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        triglicide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        triglicide.setText("Triglycérides (0,60-1,65g/l)");
        triglicide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_triglyceride.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_triglyceride.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_triglyceride.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_triglycerideActionPerformed(evt);
            }
        });
        txt_triglyceride.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_triglycerideKeyPressed(evt);
            }
        });

        txt_protine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_protine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_protine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_protineActionPerformed(evt);
            }
        });
        txt_protine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_protineKeyPressed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setText("Protéine (63-79g/l)");
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        acide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        acide.setText("Acides uriques (30-70/g/l)");
        acide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_acide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_acide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_acide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_acideActionPerformed(evt);
            }
        });
        txt_acide.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_acideKeyPressed(evt);
            }
        });

        txt_amylase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_amylase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_amylase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_amylaseActionPerformed(evt);
            }
        });
        txt_amylase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_amylaseKeyPressed(evt);
            }
        });

        amylase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        amylase.setText("Amylases");
        amylase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_sgot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_sgot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_sgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sgotActionPerformed(evt);
            }
        });
        txt_sgot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sgotKeyPressed(evt);
            }
        });

        sgot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sgot.setText("SGOT ");
        sgot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sgpt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sgpt.setText("SGPT ");
        sgpt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_sgpt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_sgpt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_sgpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sgptActionPerformed(evt);
            }
        });
        txt_sgpt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sgptKeyPressed(evt);
            }
        });

        directe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        directe.setText("Directe");
        directe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_directe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_directe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_directe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_directeActionPerformed(evt);
            }
        });
        txt_directe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_directeKeyPressed(evt);
            }
        });

        txt_libre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_libre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_libre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_libreActionPerformed(evt);
            }
        });
        txt_libre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_libreKeyPressed(evt);
            }
        });

        inderecte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inderecte.setText("Indirecte ");
        inderecte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        total.setText("Total (10 mg/l)");
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_totale.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_totale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_totale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totaleActionPerformed(evt);
            }
        });
        txt_totale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_totaleKeyPressed(evt);
            }
        });

        txt_phosph.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_phosph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_phosph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phosphActionPerformed(evt);
            }
        });
        txt_phosph.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_phosphKeyPressed(evt);
            }
        });

        phosphat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phosphat.setText("Phosphatases Acalines (21-92Ul)");
        phosphat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        phosphore.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        phosphore.setText("Phosphorémie (10-14 mg/l)");
        phosphore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_phosphor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_phosphor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_phosphor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phosphorActionPerformed(evt);
            }
        });
        txt_phosphor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_phosphorKeyPressed(evt);
            }
        });

        soduim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        soduim.setText("Sodium (134-144 MEg/l)");
        soduim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_sodium.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_sodium.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_sodium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sodiumActionPerformed(evt);
            }
        });
        txt_sodium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_sodiumKeyPressed(evt);
            }
        });

        potasuim.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        potasuim.setText("Potassium (3,8-5,4 g/l)");
        potasuim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txt_potasium.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_potasium.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_potasium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_potasiumActionPerformed(evt);
            }
        });
        txt_potasium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_potasiumKeyPressed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("TRANSAMINASES");

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("BILIRUBINE");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("AUTRES");

        jTXT_DESCRIPTION.setColumns(20);
        jTXT_DESCRIPTION.setRows(5);
        jScrollPane1.setViewportView(jTXT_DESCRIPTION);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("IONOGRAMME");

        javax.swing.GroupLayout BIOCHIMIELayout = new javax.swing.GroupLayout(BIOCHIMIE);
        BIOCHIMIE.setLayout(BIOCHIMIELayout);
        BIOCHIMIELayout.setHorizontalGroup(
            BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(BIOCHIMIELayout.createSequentialGroup()
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BIOCHIMIELayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sgpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(uree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(creatine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(glicimee, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(sgot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(12, 12, 12)
                                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_sgpt, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_sgot)
                                    .addComponent(txt_uree, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_creatine)
                                    .addComponent(txt_glycemie)))
                            .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(triglicide, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amylase, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acide, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cholesterol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lipide, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_triglyceride)
                                    .addComponent(txt_calcymie)
                                    .addComponent(txt_cholesterol)
                                    .addComponent(txt_lipide)
                                    .addComponent(txt_amylase)
                                    .addComponent(txt_acide)
                                    .addComponent(txt_protine)))
                            .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(potasuim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(soduim, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_potasium)
                                    .addComponent(txt_sodium)))
                            .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                            .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(total, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(inderecte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(12, 12, 12))
                                        .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                            .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(phosphore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(phosphat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                        .addComponent(directe, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_directe)
                                    .addComponent(txt_phosphor)
                                    .addComponent(txt_libre)
                                    .addComponent(txt_totale)
                                    .addComponent(txt_phosph)))))
                    .addGroup(BIOCHIMIELayout.createSequentialGroup()
                        .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BIOCHIMIELayout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BIOCHIMIELayout.setVerticalGroup(
            BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BIOCHIMIELayout.createSequentialGroup()
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uree)
                    .addComponent(txt_uree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_creatine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creatine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_glycemie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glicimee))
                .addGap(0, 0, 0)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_calcymie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_lipide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lipide))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_cholesterol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cholesterol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_triglyceride, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(triglicide))
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_protine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acide)
                    .addComponent(txt_acide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amylase)
                    .addComponent(txt_amylase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgot)
                    .addComponent(txt_sgot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sgpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sgpt))
                .addGap(5, 5, 5)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_directe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(directe))
                .addGap(5, 5, 5)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_libre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inderecte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_totale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addGap(4, 4, 4)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_phosph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phosphat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_phosphor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phosphore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sodium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soduim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BIOCHIMIELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_potasium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potasuim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        txt_date.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_date.setBorder(null);
        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });
        txt_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_dateKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel10)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(BIOCHIMIE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(BIOCHIMIE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_prenomActionPerformed

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

    }//GEN-LAST:event_jLabel10MouseClicked

    private void txt_nomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nomKeyPressed

        
                
               
    }//GEN-LAST:event_txt_nomKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.addActionListener(new Impression1(jPanel1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_ureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ureeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ureeActionPerformed

    private void txt_ureeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ureeKeyPressed

    }//GEN-LAST:event_txt_ureeKeyPressed

    private void txt_creatineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_creatineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_creatineActionPerformed

    private void txt_creatineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_creatineKeyPressed

    }//GEN-LAST:event_txt_creatineKeyPressed

    private void txt_glycemieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_glycemieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_glycemieActionPerformed

    private void txt_glycemieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_glycemieKeyPressed

    }//GEN-LAST:event_txt_glycemieKeyPressed

    private void txt_calcymieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_calcymieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_calcymieActionPerformed

    private void txt_calcymieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_calcymieKeyPressed

    }//GEN-LAST:event_txt_calcymieKeyPressed

    private void txt_lipideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lipideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lipideActionPerformed

    private void txt_lipideKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_lipideKeyPressed

    }//GEN-LAST:event_txt_lipideKeyPressed

    private void txt_cholesterolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cholesterolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cholesterolActionPerformed

    private void txt_cholesterolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cholesterolKeyPressed

    }//GEN-LAST:event_txt_cholesterolKeyPressed

    private void txt_triglycerideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_triglycerideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_triglycerideActionPerformed

    private void txt_triglycerideKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_triglycerideKeyPressed

    }//GEN-LAST:event_txt_triglycerideKeyPressed

    private void txt_protineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_protineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_protineActionPerformed

    private void txt_protineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_protineKeyPressed

    }//GEN-LAST:event_txt_protineKeyPressed

    private void txt_acideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_acideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_acideActionPerformed

    private void txt_acideKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_acideKeyPressed

    }//GEN-LAST:event_txt_acideKeyPressed

    private void txt_amylaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_amylaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_amylaseActionPerformed

    private void txt_amylaseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_amylaseKeyPressed

    }//GEN-LAST:event_txt_amylaseKeyPressed

    private void txt_sgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sgotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sgotActionPerformed

    private void txt_sgotKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sgotKeyPressed

    }//GEN-LAST:event_txt_sgotKeyPressed

    private void txt_sgptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sgptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sgptActionPerformed

    private void txt_sgptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sgptKeyPressed

    }//GEN-LAST:event_txt_sgptKeyPressed

    private void txt_directeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_directeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_directeActionPerformed

    private void txt_directeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_directeKeyPressed

    }//GEN-LAST:event_txt_directeKeyPressed

    private void txt_libreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_libreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_libreActionPerformed

    private void txt_libreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_libreKeyPressed

    }//GEN-LAST:event_txt_libreKeyPressed

    private void txt_totaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totaleActionPerformed

    private void txt_totaleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totaleKeyPressed

    }//GEN-LAST:event_txt_totaleKeyPressed

    private void txt_phosphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phosphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phosphActionPerformed

    private void txt_phosphKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phosphKeyPressed

    }//GEN-LAST:event_txt_phosphKeyPressed

    private void txt_phosphorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phosphorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phosphorActionPerformed

    private void txt_phosphorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phosphorKeyPressed


    }//GEN-LAST:event_txt_phosphorKeyPressed

    private void txt_sodiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sodiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sodiumActionPerformed

    private void txt_sodiumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sodiumKeyPressed

    }//GEN-LAST:event_txt_sodiumKeyPressed

    private void txt_potasiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_potasiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_potasiumActionPerformed

    private void txt_potasiumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_potasiumKeyPressed

    }//GEN-LAST:event_txt_potasiumKeyPressed

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
       
    }//GEN-LAST:event_txt_dateActionPerformed

    private void txt_ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyPressed
          
                                       
    }//GEN-LAST:event_txt_ageKeyPressed

    private void txt_dateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dateKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         
        }
    }//GEN-LAST:event_txt_dateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ETAT_BIOCHIMIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ETAT_BIOCHIMIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ETAT_BIOCHIMIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ETAT_BIOCHIMIE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ETAT_BIOCHIMIE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BIOCHIMIE;
    private javax.swing.JLabel acide;
    private javax.swing.JLabel amylase;
    private javax.swing.JLabel cholesterol;
    private javax.swing.JLabel creatine;
    private javax.swing.JLabel directe;
    private javax.swing.JLabel glicimee;
    private javax.swing.JLabel inderecte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTXT_DESCRIPTION;
    private javax.swing.JLabel lipide;
    private javax.swing.JLabel phosphat;
    private javax.swing.JLabel phosphore;
    private javax.swing.JLabel potasuim;
    private javax.swing.JLabel sgot;
    private javax.swing.JLabel sgpt;
    private javax.swing.JLabel soduim;
    private javax.swing.JLabel total;
    private javax.swing.JLabel triglicide;
    public javax.swing.JTextField txt_acide;
    public javax.swing.JTextField txt_age;
    public javax.swing.JTextField txt_amylase;
    public javax.swing.JTextField txt_calcymie;
    public javax.swing.JTextField txt_cholesterol;
    public javax.swing.JTextField txt_creatine;
    private javax.swing.JTextField txt_date;
    public javax.swing.JTextField txt_directe;
    public javax.swing.JTextField txt_glycemie;
    public javax.swing.JTextField txt_libre;
    public javax.swing.JTextField txt_lipide;
    public javax.swing.JTextField txt_nom;
    public javax.swing.JTextField txt_phosph;
    public javax.swing.JTextField txt_phosphor;
    public javax.swing.JTextField txt_potasium;
    public javax.swing.JTextField txt_prenom;
    public javax.swing.JTextField txt_protine;
    public javax.swing.JTextField txt_sgot;
    public javax.swing.JTextField txt_sgpt;
    public javax.swing.JTextField txt_sodium;
    public javax.swing.JTextField txt_totale;
    public javax.swing.JTextField txt_triglyceride;
    public javax.swing.JTextField txt_uree;
    private javax.swing.JLabel uree;
    // End of variables declaration//GEN-END:variables

}
